# Generated by Django 4.2.3 on 2023-09-26 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="comments",
            field=models.ManyToManyField(
                related_name="forum_comments",
                through="ads.Comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
