# Generated by Django 4.2.3 on 2023-09-28 15:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("ads", "0006_ad_favorites_alter_fav_thing_delete_thing"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
